#!/bin/bash

clear

show_main_menu() {
while true; do
clear
echo "#################################################################"
echo "(force-opengl-version-with-compat-profile) >> (aug 2023)"
echo "#################################################################"
echo "  ██████  ██████  ███████ ███    ██  ██████  ██      "
echo " ██    ██ ██   ██ ██      ████   ██ ██       ██      "
echo " ██    ██ ██████  █████   ██ ██  ██ ██   ███ ██      "
echo " ██    ██ ██      ██      ██  ██ ██ ██    ██ ██      "
echo "  ██████  ██      ███████ ██   ████  ██████  ███████ " 
echo "#################################################################"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
echo "(build-latest) >> (0.0.1)"
echo "(force-opengl-version-with-compat-profile-github) >> (https://github.com/manoel-linux/force-opengl-version)"
echo "#################################################################"
echo "(NOTE) >> (Some programs may have issues, and some may function without any problems)"
echo "#################################################################"

if [[ $EUID -eq 0 ]]; then
echo " ███████ ██████  ██████   ██████  ██████  ██ "
echo " ██      ██   ██ ██   ██ ██    ██ ██   ██ ██ "
echo " █████   ██████  ██████  ██    ██ ██████  ██ "
echo " ██      ██   ██ ██   ██ ██    ██ ██   ██    "
echo " ███████ ██   ██ ██   ██  ██████  ██   ██ ██ "                                                                                        
echo "#################################################################"
echo "(This script should not be executed as a superuser or sudo)"
echo "(Please run it without superuser privileges or sudo)"
echo "#################################################################"
exit 1
fi

echo "(1)> (Force) >> (the OpenGL-compat-profile version 4.6)"
echo "(2)> (Force) >> (the OpenGL-compat-profile version 4.5)"
echo "(3)> (Force) >> (the OpenGL-compat-profile version 4.4)"
echo "(4)> (Force) >> (the OpenGL-compat-profile version 4.3)"
echo "(5)> (Force) >> (the OpenGL-compat-profile version 4.2)"
echo "(6)> (Force) >> (the OpenGL-compat-profile version 4.1)"
echo "(7)> (Force) >> (the OpenGL-compat-profile version 4.0)"
echo "(8)> (Force) >> (the OpenGL-compat-profile version 3.3)"
echo "(9)> (Force) >> (the OpenGL-compat-profile version 3.2)"
echo "(10)> (Force) >> (the OpenGL-compat-profile version 3.1)"
echo "(11)> (Force) >> (the OpenGL-compat-profile version 3.0)"
echo "(12)> (Exit)"
echo "#################################################################"

read -p "(Enter your choice) >> " choice
echo "#################################################################"

case $choice in
1)
show_opengl_4_6
;;
2)
show_opengl_4_5
;;
3)
show_opengl_4_4
;;
4)
show_opengl_4_3
;;
5)
show_opengl_4_2
;;
6)
show_opengl_4_1
;;
7)
show_opengl_4_0
;;
8)
show_opengl_3_3
;;
9)
show_opengl_3_2
;;
10)
show_opengl_3_1
;;
11)
show_opengl_3_0
;;
12)
exit 0
;;
*)
echo "(Invalid choice. Please try again)"
echo "#################################################################"
sleep 2
;;
esac
done
}

show_opengl_4_6() {
while true; do
clear
echo "#################################################################"
read -p "(Enter the name of the program to configure and launch) >> " program_name
echo "#################################################################"
export MESA_GL_VERSION_OVERRIDE=4.6COMPAT
export MESA_GLSL_VERSION_OVERRIDE=460
$program_name &
exit 1

break
done

echo "#################################################################"
}

show_opengl_4_5() {
while true; do
clear
echo "#################################################################"
read -p "(Enter the name of the program to configure and launch) >> " program_name
echo "#################################################################"
export MESA_GL_VERSION_OVERRIDE=4.5COMPAT
export MESA_GLSL_VERSION_OVERRIDE=450
$program_name &
exit 1

break
done

echo "#################################################################"
}

show_opengl_4_4() {
while true; do
clear
echo "#################################################################"
read -p "(Enter the name of the program to configure and launch) >> " program_name
echo "#################################################################"
export MESA_GL_VERSION_OVERRIDE=4.4COMPAT
export MESA_GLSL_VERSION_OVERRIDE=440
$program_name &
exit 1

break
done

echo "#################################################################"
}

show_opengl_4_3() {
while true; do
clear
echo "#################################################################"
read -p "(Enter the name of the program to configure and launch) >> " program_name
echo "#################################################################"
export MESA_GL_VERSION_OVERRIDE=4.3COMPAT
export MESA_GLSL_VERSION_OVERRIDE=430
$program_name &
exit 1

break
done

echo "#################################################################"
}

show_opengl_4_2() {
while true; do
clear
echo "#################################################################"
read -p "(Enter the name of the program to configure and launch) >> " program_name
echo "#################################################################"
export MESA_GL_VERSION_OVERRIDE=4.2COMPAT
export MESA_GLSL_VERSION_OVERRIDE=420
$program_name &
exit 1

break
done

echo "#################################################################"
}

show_opengl_4_1() {
while true; do
clear
echo "#################################################################"
read -p "(Enter the name of the program to configure and launch) >> " program_name
echo "#################################################################"
export MESA_GL_VERSION_OVERRIDE=4.1COMPAT
export MESA_GLSL_VERSION_OVERRIDE=410
$program_name &
exit 1

break
done

echo "#################################################################"
}

show_opengl_4_0() {
while true; do
clear
echo "#################################################################"
read -p "(Enter the name of the program to configure and launch) >> " program_name
echo "#################################################################"
export MESA_GL_VERSION_OVERRIDE=4.0COMPAT
export MESA_GLSL_VERSION_OVERRIDE=400
$program_name &
exit 1

break
done

echo "#################################################################"
}

show_opengl_3_3() {
while true; do
clear
echo "#################################################################"
read -p "(Enter the name of the program to configure and launch) >> " program_name
echo "#################################################################"
export MESA_GL_VERSION_OVERRIDE=3.3COMPAT
export MESA_GLSL_VERSION_OVERRIDE=330
$program_name &
exit 1

break
done

echo "#################################################################"
}

show_opengl_3_2() {
while true; do
clear
echo "#################################################################"
read -p "(Enter the name of the program to configure and launch) >> " program_name
echo "#################################################################"
export MESA_GL_VERSION_OVERRIDE=3.2COMPAT
export MESA_GLSL_VERSION_OVERRIDE=150
$program_name &
exit 1

break
done

echo "#################################################################"
}

show_opengl_3_1() {
while true; do
clear
echo "#################################################################"
read -p "(Enter the name of the program to configure and launch) >> " program_name
echo "#################################################################"
export MESA_GL_VERSION_OVERRIDE=3.1COMPAT
export MESA_GLSL_VERSION_OVERRIDE=140
$program_name &
exit 1

break
done

echo "#################################################################"
}

show_opengl_3_0() {
while true; do
clear
echo "#################################################################"
read -p "(Enter the name of the program to configure and launch) >> " program_name
echo "#################################################################"
export MESA_GL_VERSION_OVERRIDE=3.0COMPAT
export MESA_GLSL_VERSION_OVERRIDE=130
$program_name &
exit 1

break
done

echo "#################################################################"
}

show_main_menu
